### ISSUE TITLE
Sorting sorts by capital letter

### ISSUE THREAD

**Issue by AlonaPF** [prashanth-sams/client-api#137]
I tried to perform sorting and i had some values with capital letter
it sorted it first and then the rest
i believe it should sort regardless

**Comment by prashanth-sams** [comment]
@AlonaPF By default, the sorting works as what we have right now (caps first and then downcase). For your solution, I would suggest you https://stackoverflow.com/questions/17799871/how-do-i-alphabetize-an-array-ignoring-case/17799952
